/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ExprCppTree.g
 *     -                            On : 2020-08-24 16:46:15
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[19+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DEF",
        (pANTLR3_UINT8) "DIVIDE",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRINT",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multExpr_return
	multExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_print_stmt_return
	print_stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_def_stmt_return
	def_stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_def_id_return
	def_id    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_code_return
	block_code    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_blocks_return
	blocks    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->print_stmt	= print_stmt;
    ctx->def_stmt	= def_stmt;
    ctx->def_id	= def_id;
    ctx->block_code	= block_code;
    ctx->blocks	= blocks;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr58  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr58_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr58	= { FOLLOW_multExpr_in_expr58_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr62  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr62_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr62	= { FOLLOW_PLUS_in_expr62_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr67  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr67	= { FOLLOW_MINUS_in_expr67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr71  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr71_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr71	= { FOLLOW_multExpr_in_expr71_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr105  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr105_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008882) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr105	= { FOLLOW_atom_in_multExpr105_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr109  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr109_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr109	= { FOLLOW_TIMES_in_multExpr109_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIVIDE_in_multExpr114  */
static	ANTLR3_BITWORD FOLLOW_DIVIDE_in_multExpr114_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_DIVIDE_in_multExpr114	= { FOLLOW_DIVIDE_in_multExpr114_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MOD_in_multExpr119  */
static	ANTLR3_BITWORD FOLLOW_MOD_in_multExpr119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_MOD_in_multExpr119	= { FOLLOW_MOD_in_multExpr119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr123  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008882) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr123	= { FOLLOW_atom_in_multExpr123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom156  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom156	= { FOLLOW_INT_in_atom156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom164  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom164	= { FOLLOW_ID_in_atom164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_atom172  */
static	ANTLR3_BITWORD FOLLOW_17_in_atom172_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_atom172	= { FOLLOW_17_in_atom172_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom175  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom175	= { FOLLOW_expr_in_atom175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_atom177  */
static	ANTLR3_BITWORD FOLLOW_18_in_atom177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_atom177	= { FOLLOW_18_in_atom177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt198  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt198_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt198	= { FOLLOW_expr_in_stmt198_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_stmt200  */
static	ANTLR3_BITWORD FOLLOW_20_in_stmt200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_stmt200	= { FOLLOW_20_in_stmt200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt202  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt202	= { FOLLOW_NEWLINE_in_stmt202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt216  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt216_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt216	= { FOLLOW_ID_in_stmt216_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt218  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt218_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt218	= { FOLLOW_ASSIGN_in_stmt218_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt220  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt220_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt220	= { FOLLOW_expr_in_stmt220_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_stmt222  */
static	ANTLR3_BITWORD FOLLOW_20_in_stmt222_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_stmt222	= { FOLLOW_20_in_stmt222_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt224  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt224_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt224	= { FOLLOW_NEWLINE_in_stmt224_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_stmt243  */
static	ANTLR3_BITWORD FOLLOW_20_in_stmt243_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_stmt243	= { FOLLOW_20_in_stmt243_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt246  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt246_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt246	= { FOLLOW_NEWLINE_in_stmt246_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_stmt_in_stmt259  */
static	ANTLR3_BITWORD FOLLOW_def_stmt_in_stmt259_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_def_stmt_in_stmt259	= { FOLLOW_def_stmt_in_stmt259_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_stmt_in_stmt267  */
static	ANTLR3_BITWORD FOLLOW_print_stmt_in_stmt267_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_stmt_in_stmt267	= { FOLLOW_print_stmt_in_stmt267_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blocks_in_stmt275  */
static	ANTLR3_BITWORD FOLLOW_blocks_in_stmt275_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_blocks_in_stmt275	= { FOLLOW_blocks_in_stmt275_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRINT_in_print_stmt287  */
static	ANTLR3_BITWORD FOLLOW_PRINT_in_print_stmt287_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_PRINT_in_print_stmt287	= { FOLLOW_PRINT_in_print_stmt287_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_print_stmt290  */
static	ANTLR3_BITWORD FOLLOW_expr_in_print_stmt290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_print_stmt290	= { FOLLOW_expr_in_print_stmt290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_print_stmt292  */
static	ANTLR3_BITWORD FOLLOW_20_in_print_stmt292_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_print_stmt292	= { FOLLOW_20_in_print_stmt292_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEF_in_def_stmt299  */
static	ANTLR3_BITWORD FOLLOW_DEF_in_def_stmt299_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_DEF_in_def_stmt299	= { FOLLOW_DEF_in_def_stmt299_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_id_in_def_stmt302  */
static	ANTLR3_BITWORD FOLLOW_def_id_in_def_stmt302_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000180000) };
static  ANTLR3_BITSET_LIST FOLLOW_def_id_in_def_stmt302	= { FOLLOW_def_id_in_def_stmt302_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_def_stmt305  */
static	ANTLR3_BITWORD FOLLOW_19_in_def_stmt305_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_def_stmt305	= { FOLLOW_19_in_def_stmt305_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_def_id_in_def_stmt308  */
static	ANTLR3_BITWORD FOLLOW_def_id_in_def_stmt308_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000180000) };
static  ANTLR3_BITSET_LIST FOLLOW_def_id_in_def_stmt308	= { FOLLOW_def_id_in_def_stmt308_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_def_stmt312  */
static	ANTLR3_BITWORD FOLLOW_20_in_def_stmt312_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_def_stmt312	= { FOLLOW_20_in_def_stmt312_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_def_id320  */
static	ANTLR3_BITWORD FOLLOW_ID_in_def_id320_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_def_id320	= { FOLLOW_ID_in_def_id320_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_def_id324  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_def_id324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_def_id324	= { FOLLOW_ASSIGN_in_def_id324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_def_id327  */
static	ANTLR3_BITWORD FOLLOW_expr_in_def_id327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_def_id327	= { FOLLOW_expr_in_def_id327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block_code349  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block_code349_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000325342) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block_code349	= { FOLLOW_stmt_in_block_code349_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_blocks357  */
static	ANTLR3_BITWORD FOLLOW_21_in_blocks357_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000725340) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_blocks357	= { FOLLOW_21_in_blocks357_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_code_in_blocks359  */
static	ANTLR3_BITWORD FOLLOW_block_code_in_blocks359_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_block_code_in_blocks359	= { FOLLOW_block_code_in_blocks359_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_blocks361  */
static	ANTLR3_BITWORD FOLLOW_22_in_blocks361_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_blocks361	= { FOLLOW_22_in_blocks361_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blocks_in_prog390  */
static	ANTLR3_BITWORD FOLLOW_blocks_in_prog390_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200002) };
static  ANTLR3_BITSET_LIST FOLLOW_blocks_in_prog390	= { FOLLOW_blocks_in_prog390_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * ExprCppTree.g:16:1: expr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS2;
    pANTLR3_COMMON_TOKEN    MINUS3;
    ExprCppTreeParser_multExpr_return multExpr1;
    #undef	RETURN_TYPE_multExpr1
    #define	RETURN_TYPE_multExpr1 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_multExpr_return multExpr4;
    #undef	RETURN_TYPE_multExpr4
    #define	RETURN_TYPE_multExpr4 ExprCppTreeParser_multExpr_return

    pANTLR3_BASE_TREE PLUS2_tree;
    pANTLR3_BASE_TREE MINUS3_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS2       = NULL;
    MINUS3       = NULL;
    multExpr1.tree = NULL;

    multExpr4.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS2_tree   = NULL;
    MINUS3_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:16:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // ExprCppTree.g:16:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr58);
            multExpr1=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr1.tree);

            // ExprCppTree.g:16:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // ExprCppTree.g:16:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // ExprCppTree.g:16:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt1=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt1=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 1;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:16:18: PLUS ^
            	        	    {
            	        	        PLUS2 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr62);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS2_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS2))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS2_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:16:26: MINUS ^
            	        	    {
            	        	        MINUS3 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr67);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS3_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS3))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS3_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr71);
            	        multExpr4=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr4.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * ExprCppTree.g:22:1: multExpr : atom ( ( TIMES ^| DIVIDE ^| MOD ^) atom )* ;
 */
static ExprCppTreeParser_multExpr_return
multExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES6;
    pANTLR3_COMMON_TOKEN    DIVIDE7;
    pANTLR3_COMMON_TOKEN    MOD8;
    ExprCppTreeParser_atom_return atom5;
    #undef	RETURN_TYPE_atom5
    #define	RETURN_TYPE_atom5 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom9;
    #undef	RETURN_TYPE_atom9
    #define	RETURN_TYPE_atom9 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE TIMES6_tree;
    pANTLR3_BASE_TREE DIVIDE7_tree;
    pANTLR3_BASE_TREE MOD8_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES6       = NULL;
    DIVIDE7       = NULL;
    MOD8       = NULL;
    atom5.tree = NULL;

    atom9.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES6_tree   = NULL;
    DIVIDE7_tree   = NULL;
    MOD8_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:23:5: ( atom ( ( TIMES ^| DIVIDE ^| MOD ^) atom )* )
        // ExprCppTree.g:23:7: atom ( ( TIMES ^| DIVIDE ^| MOD ^) atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr105);
            atom5=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom5.tree);

            // ExprCppTree.g:23:12: ( ( TIMES ^| DIVIDE ^| MOD ^) atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case DIVIDE:
                case MOD:
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ExprCppTree.g:23:13: ( TIMES ^| DIVIDE ^| MOD ^) atom
            	    {
            	        // ExprCppTree.g:23:13: ( TIMES ^| DIVIDE ^| MOD ^)
            	        {
            	            int alt3=3;
            	            switch ( LA(1) )
            	            {
            	            case TIMES:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case DIVIDE:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;
            	            case MOD:
            	            	{
            	            		alt3=3;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto rulemultExprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:23:14: TIMES ^
            	        	    {
            	        	        TIMES6 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr109);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        TIMES6_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES6))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES6_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:23:23: DIVIDE ^
            	        	    {
            	        	        DIVIDE7 = (pANTLR3_COMMON_TOKEN) MATCHT(DIVIDE, &FOLLOW_DIVIDE_in_multExpr114);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        DIVIDE7_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DIVIDE7))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DIVIDE7_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 3:
            	        	    // ExprCppTree.g:23:33: MOD ^
            	        	    {
            	        	        MOD8 = (pANTLR3_COMMON_TOKEN) MATCHT(MOD, &FOLLOW_MOD_in_multExpr119);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        MOD8_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MOD8))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MOD8_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr123);
            	        atom9=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom9.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * ExprCppTree.g:29:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT10;
    pANTLR3_COMMON_TOKEN    ID11;
    pANTLR3_COMMON_TOKEN    char_literal12;
    pANTLR3_COMMON_TOKEN    char_literal14;
    ExprCppTreeParser_expr_return expr13;
    #undef	RETURN_TYPE_expr13
    #define	RETURN_TYPE_expr13 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE INT10_tree;
    pANTLR3_BASE_TREE ID11_tree;
    pANTLR3_BASE_TREE char_literal12_tree;
    pANTLR3_BASE_TREE char_literal14_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT10       = NULL;
    ID11       = NULL;
    char_literal12       = NULL;
    char_literal14       = NULL;
    expr13.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT10_tree   = NULL;
    ID11_tree   = NULL;
    char_literal12_tree   = NULL;
    char_literal14_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:29:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt5;

            alt5=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt5=1;
            	}
                break;
            case ID:
            	{
            		alt5=2;
            	}
                break;
            case 17:
            	{
            		alt5=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // ExprCppTree.g:29:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT10 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom156);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT10));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT10_tree);


        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:30:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID11 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom164);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID11));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID11_tree);


        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:31:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_atom172);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom175);
        	        expr13=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr13.tree);

        	        char_literal14 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_atom177);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * ExprCppTree.g:36:1: stmt : ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | ( ';' )* NEWLINE ->| def_stmt | print_stmt | blocks );
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal16;
    pANTLR3_COMMON_TOKEN    NEWLINE17;
    pANTLR3_COMMON_TOKEN    ID18;
    pANTLR3_COMMON_TOKEN    ASSIGN19;
    pANTLR3_COMMON_TOKEN    char_literal21;
    pANTLR3_COMMON_TOKEN    NEWLINE22;
    pANTLR3_COMMON_TOKEN    char_literal23;
    pANTLR3_COMMON_TOKEN    NEWLINE24;
    ExprCppTreeParser_expr_return expr15;
    #undef	RETURN_TYPE_expr15
    #define	RETURN_TYPE_expr15 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr20;
    #undef	RETURN_TYPE_expr20
    #define	RETURN_TYPE_expr20 ExprCppTreeParser_expr_return

    ExprCppTreeParser_def_stmt_return def_stmt25;
    #undef	RETURN_TYPE_def_stmt25
    #define	RETURN_TYPE_def_stmt25 ExprCppTreeParser_def_stmt_return

    ExprCppTreeParser_print_stmt_return print_stmt26;
    #undef	RETURN_TYPE_print_stmt26
    #define	RETURN_TYPE_print_stmt26 ExprCppTreeParser_print_stmt_return

    ExprCppTreeParser_blocks_return blocks27;
    #undef	RETURN_TYPE_blocks27
    #define	RETURN_TYPE_blocks27 ExprCppTreeParser_blocks_return

    pANTLR3_BASE_TREE char_literal16_tree;
    pANTLR3_BASE_TREE NEWLINE17_tree;
    pANTLR3_BASE_TREE ID18_tree;
    pANTLR3_BASE_TREE ASSIGN19_tree;
    pANTLR3_BASE_TREE char_literal21_tree;
    pANTLR3_BASE_TREE NEWLINE22_tree;
    pANTLR3_BASE_TREE char_literal23_tree;
    pANTLR3_BASE_TREE NEWLINE24_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_20;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal16       = NULL;
    NEWLINE17       = NULL;
    ID18       = NULL;
    ASSIGN19       = NULL;
    char_literal21       = NULL;
    NEWLINE22       = NULL;
    char_literal23       = NULL;
    NEWLINE24       = NULL;
    expr15.tree = NULL;

    expr20.tree = NULL;

    def_stmt25.tree = NULL;

    print_stmt26.tree = NULL;

    blocks27.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal16_tree   = NULL;
    NEWLINE17_tree   = NULL;
    ID18_tree   = NULL;
    ASSIGN19_tree   = NULL;
    char_literal21_tree   = NULL;
    NEWLINE22_tree   = NULL;
    char_literal23_tree   = NULL;
    NEWLINE24_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_20   = NULL;
    #define CREATE_stream_20  if (stream_20 == NULL) {stream_20 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 20"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:36:5: ( expr ';' NEWLINE -> expr | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | ( ';' )* NEWLINE ->| def_stmt | print_stmt | blocks )

            ANTLR3_UINT32 alt7;

            alt7=6;

            switch ( LA(1) )
            {
            case INT:
            case 17:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt7=2;
            			}
            		    break;
            		case DIVIDE:
            		case MINUS:
            		case MOD:
            		case PLUS:
            		case TIMES:
            		case 20:
            			{
            				alt7=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 7;
            		    EXCEPTION->state        = 2;


            		    goto rulestmtEx;

            		}

            	}
                break;
            case NEWLINE:
            case 20:
            	{
            		alt7=3;
            	}
                break;
            case DEF:
            	{
            		alt7=4;
            	}
                break;
            case PRINT:
            	{
            		alt7=5;
            	}
                break;
            case 21:
            	{
            		alt7=6;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ExprCppTree.g:36:7: expr ';' NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt198);
        	        expr15=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr15.tree, NULL);

        	        char_literal16 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_stmt200);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_20; stream_20->add(stream_20, char_literal16, NULL);


        	        NEWLINE17 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt202);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE17, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 36:24: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:37:7: ID ASSIGN expr ';' NEWLINE
        	    {
        	        ID18 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt216);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID18, NULL);


        	        ASSIGN19 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt218);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN19, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt220);
        	        expr20=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr20.tree, NULL);

        	        char_literal21 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_stmt222);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_20; stream_20->add(stream_20, char_literal21, NULL);


        	        NEWLINE22 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt224);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE22, NULL);


        	        /* AST REWRITE
        	         * elements          : ASSIGN, expr, ID
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 37:34: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ExprCppTree.g:37:37: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:38:7: ( ';' )* NEWLINE
        	    {
        	        // ExprCppTree.g:38:7: ( ';' )*

        	        for (;;)
        	        {
        	            int alt6=2;
        	            switch ( LA(1) )
        	            {
        	            case 20:
        	            	{
        	            		alt6=1;
        	            	}
        	                break;

        	            }

        	            switch (alt6)
        	            {
        	        	case 1:
        	        	    // ExprCppTree.g:38:7: ';'
        	        	    {
        	        	        char_literal23 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_stmt243);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulestmtEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_20; stream_20->add(stream_20, char_literal23, NULL);


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop6;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop6: ; /* Jump out to here if this rule does not match */


        	        NEWLINE24 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt246);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE24, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 38:20: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // ExprCppTree.g:39:7: def_stmt
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_def_stmt_in_stmt259);
        	        def_stmt25=def_stmt(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, def_stmt25.tree);

        	    }
        	    break;
        	case 5:
        	    // ExprCppTree.g:40:7: print_stmt
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_print_stmt_in_stmt267);
        	        print_stmt26=print_stmt(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, print_stmt26.tree);

        	    }
        	    break;
        	case 6:
        	    // ExprCppTree.g:41:7: blocks
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_blocks_in_stmt275);
        	        blocks27=blocks(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, blocks27.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_20 != NULL) stream_20->free(stream_20);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start print_stmt
 * ExprCppTree.g:44:1: print_stmt : PRINT ^ expr ';' !;
 */
static ExprCppTreeParser_print_stmt_return
print_stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_print_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PRINT28;
    pANTLR3_COMMON_TOKEN    char_literal30;
    ExprCppTreeParser_expr_return expr29;
    #undef	RETURN_TYPE_expr29
    #define	RETURN_TYPE_expr29 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE PRINT28_tree;
    pANTLR3_BASE_TREE char_literal30_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PRINT28       = NULL;
    char_literal30       = NULL;
    expr29.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PRINT28_tree   = NULL;
    char_literal30_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:44:11: ( PRINT ^ expr ';' !)
        // ExprCppTree.g:44:13: PRINT ^ expr ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            PRINT28 = (pANTLR3_COMMON_TOKEN) MATCHT(PRINT, &FOLLOW_PRINT_in_print_stmt287);
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }

            PRINT28_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PRINT28))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PRINT28_tree, root_0));


            FOLLOWPUSH(FOLLOW_expr_in_print_stmt290);
            expr29=expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, expr29.tree);

            char_literal30 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_print_stmt292);
            if  (HASEXCEPTION())
            {
                goto ruleprint_stmtEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprint_stmtEx; /* Prevent compiler warnings */
    ruleprint_stmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end print_stmt */

/**
 * $ANTLR start def_stmt
 * ExprCppTree.g:45:1: def_stmt : DEF ^ def_id ( ',' ! def_id )* ';' !;
 */
static ExprCppTreeParser_def_stmt_return
def_stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_def_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DEF31;
    pANTLR3_COMMON_TOKEN    char_literal33;
    pANTLR3_COMMON_TOKEN    char_literal35;
    ExprCppTreeParser_def_id_return def_id32;
    #undef	RETURN_TYPE_def_id32
    #define	RETURN_TYPE_def_id32 ExprCppTreeParser_def_id_return

    ExprCppTreeParser_def_id_return def_id34;
    #undef	RETURN_TYPE_def_id34
    #define	RETURN_TYPE_def_id34 ExprCppTreeParser_def_id_return

    pANTLR3_BASE_TREE DEF31_tree;
    pANTLR3_BASE_TREE char_literal33_tree;
    pANTLR3_BASE_TREE char_literal35_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    DEF31       = NULL;
    char_literal33       = NULL;
    char_literal35       = NULL;
    def_id32.tree = NULL;

    def_id34.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DEF31_tree   = NULL;
    char_literal33_tree   = NULL;
    char_literal35_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:45:9: ( DEF ^ def_id ( ',' ! def_id )* ';' !)
        // ExprCppTree.g:45:11: DEF ^ def_id ( ',' ! def_id )* ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            DEF31 = (pANTLR3_COMMON_TOKEN) MATCHT(DEF, &FOLLOW_DEF_in_def_stmt299);
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }

            DEF31_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DEF31))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DEF31_tree, root_0));


            FOLLOWPUSH(FOLLOW_def_id_in_def_stmt302);
            def_id32=def_id(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, def_id32.tree);

            // ExprCppTree.g:45:23: ( ',' ! def_id )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case 19:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // ExprCppTree.g:45:24: ',' ! def_id
            	    {
            	        char_literal33 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_def_stmt305);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_stmtEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_def_id_in_def_stmt308);
            	        def_id34=def_id(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_stmtEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, def_id34.tree);

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


            char_literal35 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_def_stmt312);
            if  (HASEXCEPTION())
            {
                goto ruledef_stmtEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledef_stmtEx; /* Prevent compiler warnings */
    ruledef_stmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end def_stmt */

/**
 * $ANTLR start def_id
 * ExprCppTree.g:46:1: def_id : ID ^ ( ASSIGN ! expr )? ;
 */
static ExprCppTreeParser_def_id_return
def_id(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_def_id_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ID36;
    pANTLR3_COMMON_TOKEN    ASSIGN37;
    ExprCppTreeParser_expr_return expr38;
    #undef	RETURN_TYPE_expr38
    #define	RETURN_TYPE_expr38 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE ID36_tree;
    pANTLR3_BASE_TREE ASSIGN37_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    ID36       = NULL;
    ASSIGN37       = NULL;
    expr38.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ID36_tree   = NULL;
    ASSIGN37_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:46:7: ( ID ^ ( ASSIGN ! expr )? )
        // ExprCppTree.g:46:9: ID ^ ( ASSIGN ! expr )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            ID36 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_def_id320);
            if  (HASEXCEPTION())
            {
                goto ruledef_idEx;
            }

            ID36_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID36))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ID36_tree, root_0));


            // ExprCppTree.g:46:13: ( ASSIGN ! expr )?
            {
                int alt9=2;
                switch ( LA(1) )
                {
                    case ASSIGN:
                    	{
                    		alt9=1;
                    	}
                        break;
                }

                switch (alt9)
                {
            	case 1:
            	    // ExprCppTree.g:46:14: ASSIGN ! expr
            	    {
            	        ASSIGN37 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_def_id324);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_idEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_expr_in_def_id327);
            	        expr38=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledef_idEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, expr38.tree);

            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledef_idEx; /* Prevent compiler warnings */
    ruledef_idEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end def_id */

/**
 * $ANTLR start block_code
 * ExprCppTree.g:50:1: block_code : ( stmt )* ;
 */
static ExprCppTreeParser_block_code_return
block_code(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_code_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt39;
    #undef	RETURN_TYPE_stmt39
    #define	RETURN_TYPE_stmt39 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt39.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:50:12: ( ( stmt )* )
        // ExprCppTree.g:50:14: ( stmt )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:50:14: ( stmt )*

            for (;;)
            {
                int alt10=2;
                switch ( LA(1) )
                {
                case DEF:
                case ID:
                case INT:
                case NEWLINE:
                case PRINT:
                case 17:
                case 20:
                case 21:
                	{
                		alt10=1;
                	}
                    break;

                }

                switch (alt10)
                {
            	case 1:
            	    // ExprCppTree.g:50:14: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block_code349);
            	        stmt39=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblock_codeEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, stmt39.tree);

            	    }
            	    break;

            	default:
            	    goto loop10;	/* break out of the loop */
            	    break;
                }
            }
            loop10: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_codeEx; /* Prevent compiler warnings */
    ruleblock_codeEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block_code */

/**
 * $ANTLR start blocks
 * ExprCppTree.g:51:1: blocks : '{' block_code '}' -> ^( BLOCK block_code ) ;
 */
static ExprCppTreeParser_blocks_return
blocks(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_blocks_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal40;
    pANTLR3_COMMON_TOKEN    char_literal42;
    ExprCppTreeParser_block_code_return block_code41;
    #undef	RETURN_TYPE_block_code41
    #define	RETURN_TYPE_block_code41 ExprCppTreeParser_block_code_return

    pANTLR3_BASE_TREE char_literal40_tree;
    pANTLR3_BASE_TREE char_literal42_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_22;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_21;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block_code;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal40       = NULL;
    char_literal42       = NULL;
    block_code41.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal40_tree   = NULL;
    char_literal42_tree   = NULL;

    stream_22   = NULL;
    #define CREATE_stream_22  if (stream_22 == NULL) {stream_22 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 22"); } 
    stream_21   = NULL;
    #define CREATE_stream_21  if (stream_21 == NULL) {stream_21 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 21"); } 
    stream_block_code   = NULL;
    #define CREATE_stream_block_code  if (stream_block_code == NULL) {stream_block_code = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block_code"); }

    retval.tree  = NULL;

    {
        // ExprCppTree.g:51:8: ( '{' block_code '}' -> ^( BLOCK block_code ) )
        // ExprCppTree.g:51:10: '{' block_code '}'
        {
            char_literal40 = (pANTLR3_COMMON_TOKEN) MATCHT(21, &FOLLOW_21_in_blocks357);
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }
             
            CREATE_stream_21; stream_21->add(stream_21, char_literal40, NULL);


            FOLLOWPUSH(FOLLOW_block_code_in_blocks359);
            block_code41=block_code(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }

            CREATE_stream_block_code; stream_block_code->add(stream_block_code, block_code41.tree, NULL);

            char_literal42 = (pANTLR3_COMMON_TOKEN) MATCHT(22, &FOLLOW_22_in_blocks361);
            if  (HASEXCEPTION())
            {
                goto ruleblocksEx;
            }
             
            CREATE_stream_22; stream_22->add(stream_22, char_literal42, NULL);


            /* AST REWRITE
             * elements          : block_code
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 51:29: -> ^( BLOCK block_code )
            	{
            	    // ExprCppTree.g:51:32: ^( BLOCK block_code )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block_code == NULL ? NULL : stream_block_code->nextTree(stream_block_code));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblocksEx; /* Prevent compiler warnings */
    ruleblocksEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_22 != NULL) stream_22->free(stream_22);
        if (stream_21 != NULL) stream_21->free(stream_21);
        if (stream_block_code != NULL) stream_block_code->free(stream_block_code);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end blocks */

/**
 * $ANTLR start prog
 * ExprCppTree.g:55:1: prog : ( blocks )+ ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_blocks_return blocks43;
    #undef	RETURN_TYPE_blocks43
    #define	RETURN_TYPE_blocks43 ExprCppTreeParser_blocks_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    blocks43.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:56:5: ( ( blocks )+ )
        // ExprCppTree.g:56:7: ( blocks )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:56:7: ( blocks )+
            {
                int cnt11=0;

                for (;;)
                {
                    int alt11=2;
            	switch ( LA(1) )
            	{
            	case 21:
            		{
            			alt11=1;
            		}
            	    break;

            	}

            	switch (alt11)
            	{
            	    case 1:
            	        // ExprCppTree.g:56:9: blocks
            	        {
            	            FOLLOWPUSH(FOLLOW_blocks_in_prog390);
            	            blocks43=blocks(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, blocks43.tree);

            	            {

            	                            pANTLR3_STRING s = (blocks43.tree)->toStringTree((blocks43.tree));
            	                            assert(s->chars);
            	                            printf(" tree %s\n", s->chars);
            	                            
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt11 >= 1 )
            		{
            		    goto loop11;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt11++;
                }
                loop11: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
